### ISSUE TITLE
I had some issues with installing datamanger the correct way

### ISSUE THREAD

**Issue by nexitem** [tes3mp-scripts/DataManager#1]
**DataManager = require("custom.DataManager.main")**

needs to be in **customScripts.lua** and not just **require("custom.DataManager.main")** or it won't work. You seem to not state this anywhere?

**Comment by uramer** [comment]
technically, it is stated here https://github.com/tes3mp-scripts/Tutorials
although that tutorial isn't particularly readable for people who don't know anything about code

**Comment by nexitem** [comment]
Nice, well I think you should add it to the readme of your script so noone else gets confused.

I'm no programmer, I know only the very basics and it took me a bit to understand why I had errors.
