### ISSUE TITLE
Add ability to specify JSON key order

### ISSUE THREAD

**Issue by IllyaMoskvin** [tes3mp-scripts/DataManager#2]
Currently, when DataManager saves a JSON file, it uses what appears to be a random key order.

For `__data_*` files, this doesn't matter all that much, but for `__config_*` files, this isn't ideal. These config files are generally meant to be editable, and it's not a great experience for the user to have the options in there be completely mixed up relative to what the documentation and/or code references.

Under the hood, DataManager uses `jsonInterface` and its `save` method. This method provides a third parameter to specify a key order:

```
function jsonInterface.save(fileName, data, keyOrderArray)
```

It might be nice if this parameter was exposed in DataManager's API.

**Comment by uramer** [comment]
Hey! Sorry for not responding for a while.
This is a very reasonable request and I've just added this feature
